admins:
- ggeorg02
gh-pages: true
instructors:
- ggeorg02
project_repo: UBC-MDS/DSCI_532_vis-2_book
project_title: testchoo
questions: true
students: []
votes_required: 3
web_address: https://ubc-mds.github.io/DSCI_532_vis-2_book
