# Key settings (must edit)
project_title: testchoo
project_repo: UBC-MDS/DSCI_532_vis-2_book
admins:
- ggeorg02
instructors:
- ggeorg02
students:
- ilyamusabirov
web_address: https://ubc-mds.github.io/DSCI_532_vis-2_book

# User options (may edit)
questions: true
votes_required: 3
gh-pages: true



